name: Awesome-azd and Exec Docs Sync
permissions:
  actions: write
  contents: write
on:
  workflow_dispatch:

jobs:
    Commit-Workloads:
      runs-on: ubuntu-latest
      environment: "AzD Integration"

      steps:
        - name: Checkout respository
          uses: actions/checkout@v2
          with:
            ref: users/jbrockett/autoIntegrate
          
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r ${{ github.workspace }}/scripts/generate_fields/requirements.txt

        - name: Fetch workloads from azd and exec docs scenarios
          run: |
            curl -o ${{ github.workspace }}/templates.json https://raw.githubusercontent.com/Azure/awesome-azd/main/website/static/templates.json
            curl -o ${{ github.workspace }}/exec_metadata.json https://raw.githubusercontent.com/MicrosoftDocs/executable-docs/main/scenarios/metadata.json

        - name: Updating Workloads
          run: |
            echo "Running script"
            python ${{ github.workspace }}/scripts/add_workloads/add_azd.py --root ${{ github.workspace }} --input_file ${{ github.workspace }}/templates.json
            python ${{ github.workspace }}/scripts/add_workloads/add_exec_docs.py --root ${{ github.workspace }} --input_file ${{ github.workspace }}/exec_metadata.json
            rm ${{ github.workspace }}/templates.json
            rm ${{ github.workspace }}/exec_metadata.json

        - name: Generating Fields
          env:
            AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
            AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          run: |
            echo "Generating New Fields"

        - name: Configure Git
          run: |
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'

        - name: Raise PR
          uses: peter-evans/create-pull-request@v4
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            branch: "auto-pr-branch"
            commit-message: "Automated update of workloads.json"
            title: "Automated PR for update of workloads.json"
            body: "Automated update of workloads.json"
            author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
            labels: "automated-pr"
            reviewers: ${{ github.actor }}
            delete-branch: true
    
        # - name: Commit changes
        #   uses: stefanzweifel/git-auto-commit-action@v5
        #   with:
        #     create_branch: true
        #     branch: update-workloads
        #     push_options: '--force'
        #     commit_message: "Automated update of workloads.json"
        #     file_pattern: workloads/workloads.json

    # Create-PR:
    #   runs-on: ubuntu-latest
    #   needs: Commit-Workloads
    #   steps:
    #     - name: Checkout respository
    #       uses: actions/checkout@v2
    #       with:
    #         ref: dev

    #     - name: Create Pull Request
    #       uses: peter-evans/create-pull-request@v4
    #       with:
    #         token: ${{ secrets.GITHUB_TOKEN }}
    #         commit-message: "Triggered update of workloads.json"
    #         title: "Triggered PR for update of workloads.json"
    #         body: "Automated update of workloads.json"
    #         branch:  update-workloads
    #         labels: "automated-pr"
    #         reviewers: ${{ github.actor }}